### PR TITLE
ci(terraform): Test workflow changes from #57

### PR DESCRIPTION
**Pull request by chris3ware**
PR #57 submitted by @rdhar suggested using [TF-via-PR](https://github.com/marketplace/actions/terraform-opentofu-via-pull-request) for `fmt`,`validate` and updating pull request comments. This PR has been raised to test those changes.

### CODE REVIEW

**Comment by chris3ware** [comment]
`fmt` failure tested successfully.

**Comment by chris3ware** [comment]
`validate` error tested successfully. PR comment updated.

**Comment by rdhar** [comment]
So close to a 3 for 3(!) 

Will take a peek at troubleshooting "sed: -e expression #1, char 25: unterminated `s' command".

**Comment by rdhar** [comment]
Oops, that got merged a li'l prematurely: #60 should address the string substitution problem.

**Comment by chris3ware** [comment]
TFLint error tested successfully and PR comment updated.

**Review by james3ware — APPROVED** [review]

**Review by GalaxyToy — COMMENTED** [review]
Thanks for the update on this email address is it just to confirm that I have the same thing as you are doing a good job... thank you everyone.

**Pull request merged**
